install:
	mvn install

run:
	mvn exec:java -Dexec.mainClass="cs.lab.CSTranslator"

comp:
	mvn compile

test:
	mvn test

test-sonar:
	mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar